The Seller and User -  list products
atlp-rwanda/e-commerce-ninjas-bn pull request #58
Opened 2024-06-07 02:18 UTC by ndahimana154

2024-06-07 05:38 UTC, ProgrammerDATCH requested changes
You mixed middlewares with Controller.

2024-06-07 05:59 UTC, Jadowacu1 submitted a review, later dismissed

2024-06-07 08:26 UTC, MANISHIMWESalton submitted a review, later dismissed

2024-06-08 10:04 UTC, Jadowacu1 approved these changes, later dismissed

2024-06-10 00:26 UTC, AimePazzo commented on src/middlewares/validation.ts
> +const sellersShop = async (req: any, res: Response, next: NextFunction) => {
this function middleware is the same as `IsSellerShopExist` just use one

2024-06-10 00:26 UTC, AimePazzo commented on src/middlewares/validation.ts
> +const isProductsByCategorySelected = async (req: Request, res: Response, next: NextFunction) => {
Also, 'isProductsbyCategorySelected' is essentially the same as 'productsByCategory'. It seems like you are duplicating functions.

2024-06-10 06:53 UTC, Jadowacu1 submitted a review, later dismissed

2024-06-10 07:01 UTC, MANISHIMWESalton submitted a review, later dismissed

2024-06-10 14:45 UTC, Jadowacu1 approved these changes

2024-06-10 14:53 UTC, SaddockAime submitted a review, later dismissed

2024-06-10 14:54 UTC, Jadowacu1 approved these changes, later dismissed

2024-06-10 14:54 UTC, AimePazzo approved these changes

2024-06-10 14:57 UTC, ProgrammerDATCH submitted a review, later dismissed

2024-06-10 15:00 UTC, solangeihirwe03 approved these changes, later dismissed

2024-06-11 08:13 UTC, MANISHIMWESalton approved these changes, later dismissed

2024-06-11 08:23 UTC, Y-elv submitted a review, later dismissed
you did good

2024-06-11 08:26 UTC, SaddockAime submitted a review, later dismissed

2024-06-11 09:16 UTC, Jadowacu1 submitted a review, later dismissed

2024-06-11 10:06 UTC, MANISHIMWESalton approved these changes, later dismissed

2024-06-11 10:08 UTC, AimePazzo approved these changes

2024-06-11 10:14 UTC, SaddockAime submitted a review, later dismissed

2024-06-11 10:15 UTC, Jadowacu1 approved these changes, later dismissed

2024-06-11 14:15 UTC, Jadowacu1 approved these changes, later dismissed

2024-06-11 16:12 UTC, Jadowacu1 approved these changes

2024-06-11 16:13 UTC, MANISHIMWESalton approved these changes

2024-06-11 16:16 UTC, hbapte approved these changes

2024-06-11 16:53 UTC, merged