Ft buyer track order status #187584937
atlp-rwanda/e-commerce-ninjas-bn pull request #74
Opened 2024-06-18 16:16 UTC by solangeihirwe03

2024-06-19 11:15 UTC, Jadowacu1 requested changes, later dismissed
<img width="391" alt="review" src="https://github.com/atlp-rwanda/e-commerce-ninjas-bn/assets/152473876/80febfa0-1a3e-418d-84e2-72ec331dda13">

change this filename to 20240612090847-create-productReviews.ts

2024-06-21 10:39 UTC, key-joshua commented on src/routes/cartRouter.ts
> +router.get("/user-get-order-status/:id",userAuthorization(["buyer"]), validation(orderStatusSchema), cartControllers.buyerGetOrderStatus )
We don't send body request with GET Method.

2024-06-21 10:41 UTC, key-joshua commented on src/routes/cartRouter.ts
> +router.get("/user-get-order-status/:id",userAuthorization(["buyer"]), validation(orderStatusSchema), cartControllers.buyerGetOrderStatus )
Again, I have seen you are sending the `**id** ` into the body request at the same time sending the **`id`** into params, this is wrong logic.

2024-06-26 06:28 UTC, ndahimana154 approved these changes, later dismissed

2024-06-26 07:41 UTC, Fabrice-Dush approved these changes, later dismissed

2024-06-26 07:45 UTC, SaddockAime approved these changes, later dismissed

2024-06-26 09:49 UTC, Y-elv submitted a review, later dismissed

2024-06-26 09:55 UTC, hbapte approved these changes, later dismissed

2024-06-26 10:18 UTC, key-joshua commented on src/routes/cartRouter.ts
> +router.post("/user-get-order-status",userAuthorization(["buyer"]),validation(orderStatusSchema),isOrderExist, cartControllers.buyerGetOrderStatus )
Instead of sending orderId into the body send it into the params, And use GET method instead of POST method.

2024-06-26 10:19 UTC, key-joshua commented on src/routes/cartRouter.ts
> +router.post("/user-get-order-status",userAuthorization(["buyer"]),validation(orderStatusSchema),isOrderExist, cartControllers.buyerGetOrderStatus )
After changing those things remember to delete  **`orderStatusSchema`**.

2024-06-26 10:21 UTC, key-joshua commented on src/routes/cartRouter.ts
> +router.put("/admin-update-order-status", userAuthorization(["admin"]),validation(updateOrderStatusSchema),isOrderExist, cartControllers.adminUpdateOrderStatus)
I can't see the **`orderId`** you will update into the params.

2024-06-26 10:24 UTC, key-joshua commented on src/modules/cart/controller/cartControllers.ts
> +
Where is the use of web sockets to update the status in real-time

2024-06-27 06:39 UTC, key-joshua commented on src/modules/cart/controller/cartControllers.ts
> +
Please use try and catch

2024-07-01 09:40 UTC, Fabrice-Dush approved these changes, later dismissed

2024-07-07 20:02 UTC, ndahimana154 approved these changes, later dismissed
Looks fine and clean

2024-07-16 17:31 UTC, solangeihirwe03 commented
> <img alt="review" width="391" src="https://private-user-images.githubusercontent.com/152473876/341046010-80febfa0-1a3e-418d-84e2-72ec331dda13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTEzNTMsIm5iZiI6MTcyMTE1MTA1MywicGF0aCI6Ii8xNTI0NzM4NzYvMzQxMDQ2MDEwLTgwZmViZmEwLTFhM2UtNDE4ZC04NGUyLTcyZWMzMzFkZGExMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxNzMwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTI4MDMwMzJhNzk0YjFhYjliMmEzMTcyMjgzYzRmZTQzMjY3MjI1MDU2YjYyN2MxNmY3NWVmOTcwZTdmMGZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LXrbWQKDWdFuRt79hWHiQMZl9ITEUDz89AKS_bfwMx4">
> change this filename to 20240612090847-create-productReviews.ts

this migration belong to product reviewa

2024-07-16 18:28 UTC, merged