[Delivers-18758493] ft-buyer-checkout
atlp-rwanda/e-commerce-ninjas-bn pull request #77
Opened 2024-06-19 12:27 UTC by MANISHIMWESalton

2024-06-19 13:27 UTC, hbapte submitted a review, later dismissed

2024-06-19 13:30 UTC, Jadowacu1 requested changes

2024-06-19 13:30 UTC, Jadowacu1 commented on src/modules/cart/controller/cartControllers.ts
> +  userCheckout
instead of using userCheckout use buyerCheckout

2024-06-19 14:33 UTC, Jadowacu1 approved these changes, later dismissed

2024-06-19 15:32 UTC, ndahimana154 approved these changes, later dismissed

2024-06-19 21:07 UTC, Jadowacu1 submitted a review, later dismissed

2024-06-19 21:10 UTC, Fabrice-Dush submitted a review, later dismissed

2024-06-20 11:57 UTC, ProgrammerDATCH approved these changes, later dismissed

2024-06-20 12:08 UTC, hbapte approved these changes, later dismissed

2024-06-21 15:00 UTC, hbapte submitted a review, later dismissed

2024-06-22 10:35 UTC, ndahimana154 approved these changes, later dismissed
Duplicate hitting of the Database removed by using includes.

2024-06-22 11:23 UTC, ProgrammerDATCH requested changes

2024-06-22 11:23 UTC, ProgrammerDATCH commented on src/modules/cart/repositories/cartRepositories.ts
> +const findCartProductsByAttribute = async (value: any) => {
Function name is different to how it behave,
Call it findCartProductsByCartId. or simply pass in key instead of hardcoding "cartId"

2024-06-22 13:45 UTC, ProgrammerDATCH approved these changes

2024-06-22 15:02 UTC, ndahimana154 approved these changes

2024-06-22 15:26 UTC, Y-elv approved these changes

2024-06-22 15:27 UTC, hbapte approved these changes

2024-06-22 15:43 UTC, Fabrice-Dush approved these changes

2024-06-22 16:48 UTC, AimePazzo approved these changes

2024-06-22 18:06 UTC, merged